@api = http://localhost:5000/api/
### getProducts
GET {{api}}/products/

### getProductById
GET {{api}}/products/3

GET http://localhost:5000/api/products

### getBasketById
GET {{api}}/basket
# headers

# {
#     "cookie": "dbe0a1e8-4fe0-4b4f-81bc-5ff501bade87"
# }

### addItemToBasket
POST {{api}}/basket?productId=2&quantity=50

# Content-Type: application/json
# {
#     "productId": 2,
#     "quantity": 50
# }

